steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/whatsapp:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/whatsapp:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "whatsapp"
      - "--image"
      - "gcr.io/$PROJECT_ID/whatsapp:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--concurrency"
      - "1000"
      - "--cpu"
      - "1"
      - "--memory"
      - "512Mi"
      - "--port"
      - "4747"
      - "--timeout"
      - "2m"
      - "--max-instances"
      - "1000"
images:
  - "gcr.io/$PROJECT_ID/whatsapp:$COMMIT_SHA"
